server:
  port: 8080
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: your email
    password: your password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  output:
    ansi:
      enabled: always